/******************************************************************************* 
* Copyright (C) Marvell International Ltd. and its affiliates 
* 
* Marvell GPL License Option 
* 
* If you received this File from Marvell, you may opt to use, redistribute and/or 
* modify this File in accordance with the terms and conditions of the General 
* Public License Version 2, June 1991 (the "GPL License"), a copy of which is 
* available along with the File in the license.txt file or by writing to the Free 
* Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 or 
* on the worldwide web at http://www.gnu.org/licenses/gpl.txt.  
* 
* THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED 
* WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY 
* DISCLAIMED.  The GPL License provides additional details about this warranty 
* disclaimer.  
********************************************************************************/

#ifndef __GALOIS_PLATFORM_H
#define __GALOIS_PLATFORM_H


#ifdef CONFIG_MV88DE3100_ASIC
  #define GALOIS_CPU_CLK 600000000
  #define GALOIS_TIMER_CLK 75000000
  #define GALOIS_UART_TCLK 25000000
#else	/* FPGA platform */
  #define GALOIS_CPU_CLK 36000000
  #define GALOIS_TIMER_CLK 1500000
  #define GALOIS_UART_TCLK 6000000
#endif /* ASIC */

#define MEMMAP_SDIO3_REG_BASE		0xF7AB0000
#define MEMMAP_CPU_SL2C_REG_BASE	0xF7AC0000
#define MEMMAP_CPU_PMR_REG_BASE		0xF7AD0000
#define MEMMAP_AVIO_BCM_REG_BASE	0xF7B50000
#define MEMMAP_SDIO1_REG_BASE		0xF7B80000
#define MEMMAP_ETHERNET1_REG_BASE	0xF7B90000
#define MEMMAP_SDIO_REG_BASE		0xF7D50000
#define MEMMAP_PB_REG_BASE		0xF7D70000
#define MEMMAP_APBPERIF_REG_BASE	0xF7E80000
#define MEMMAP_SATA_REG_BASE		0xF7E90000
#define MEMMAP_CHIP_CTRL_REG_BASE	0xF7EA0000
#define MEMMAP_USB0_REG_BASE		0xF7ED0000
#define MEMMAP_USB1_REG_BASE		0xF7EE0000
#define MEMMAP_NAND_FLASH_REG_BASE	0xF7F00000
#define MEMMAP_PWM_REG_BASE		0xF7F20000
#define MEMMAP_SM_REG_BASE		0xF7F80000

#define MEMMAP_GIC_CPU_BASE		(MEMMAP_CPU_PMR_REG_BASE + 0x100)
#define MEMMAP_GIC_DIST_BASE		(MEMMAP_CPU_PMR_REG_BASE + 0x1000)

#define APB_GPIO_INST0_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x0400)
#define APB_GPIO_INST1_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x0800)
#define APB_GPIO_INST2_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x0C00)
#define APB_GPIO_INST3_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x1000)
#define APB_I2C_INST0_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x1400)
#define APB_I2C_INST1_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x1800)
#define APB_SSI_INST1_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x1C00)
#define APB_WDT_INST0_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x2000)
#define APB_WDT_INST1_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x2400)
#define APB_WDT_INST2_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x2800)
#define APB_TIMER_INST_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x2C00)
#define APB_ICTL_INST0_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x3000)
#define APB_ICTL_INST1_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x3400)
#define APB_ICTL_INST2_BASE		(MEMMAP_APBPERIF_REG_BASE + 0x3800)

#define SOC_SM_APB_REG_BASE		(MEMMAP_SM_REG_BASE + 0x40000)

#define SM_APB_GPIO1_BASE		(SOC_SM_APB_REG_BASE + 0x5000)
#define SM_APB_SPI_BASE			(SOC_SM_APB_REG_BASE + 0x6000)
#define APB_SSI_INST2_BASE		(SM_APB_SPI_BASE)
#define SM_APB_I2C0_BASE		(SOC_SM_APB_REG_BASE + 0x7000)
#define APB_I2C_INST2_BASE		SM_APB_I2C0_BASE
#define SM_APB_I2C1_BASE		(SOC_SM_APB_REG_BASE + 0x8000)
#define APB_I2C_INST3_BASE		SM_APB_I2C1_BASE
#define APB_UART_INST0_BASE		(SOC_SM_APB_REG_BASE + 0x9000)
#define APB_UART_INST1_BASE		(SOC_SM_APB_REG_BASE + 0xA000)
#define SM_APB_GPIO0_BASE		(SOC_SM_APB_REG_BASE + 0xC000)
#define SM_APB_GPIO_BASE		(SM_APB_GPIO0_BASE)
#define SM_SYS_CTRL_REG_BASE		(SOC_SM_APB_REG_BASE + 0xD000)
#define SM_APB_ICTL1_BASE		(SOC_SM_APB_REG_BASE + 0xE000)

#define MEMMAP_ETHERNET1_REG_SIZE	0x10000
#define MEMMAP_SATA_REG_SIZE		0x10000
#define MEMMAP_SDIO_REG_SIZE		0x10000
#define MEMMAP_SDIO1_REG_SIZE		0x10000
#define MEMMAP_SDIO3_REG_SIZE		0x10000
#define MEMMAP_NAND_FLASH_REG_SIZE	0x10000
#define MEMMAP_USB0_REG_SIZE		0x10000
#define MEMMAP_USB1_REG_SIZE		0x10000

#endif
